export const FETCH_BOOKING_DATA_PENDING = 'FETCH_BOOKING_DATA_PENDING';
export const FETCH_BOOKING_DATA_FULFILLED = 'FETCH_BOOKING_DATA_FULFILLED';

export const FETCH_FLIGHTS_PENDING = 'FETCH_FLIGHTS_PENDING';
export const FETCH_FLIGHTS_FULFILLED = 'FETCH_FLIGHTS_FULFILLED';

export const UPDATE_ORIGIN = 'UPDATE_ORIGIN';
export const UPDATE_DESTINATION = 'UPDATE_DESTINATION';
export const UPDATE_FROM_DATE = 'UPDATE_FROM_DATE';
export const UPDATE_TO_DATE = 'UPDATE_TO_DATE';
